spring:
  datasource:
    url: jdbc:mysql://106.13.73.88:3306/littleflydragon?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false
    username: root
    password: feilong@1993
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: hope-controller-app
  cloud:
    discovery:
      enabled: true

server:
  port: 4672
eureka:
  client:
    service-url:
      defaultZone: http://hopeuser:hopepassword123@mireureka:4670/eureka/
    instance:
      prefer-ip-address: true
      instance-id: hope-controller-client
    fetch-registry: true
    register-with-eureka: true


#在application.yml中加入全局调用的变量是使用instance开头，子类就可以根据要求自己定义了
instance:
  Service:
    ServiceName: hope-service-app
    ServiceHost: http://localhost:4671