spring:
  datasource:
    url: jdbc:mysql://121.36.66.235:3306/chatcloud?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false
    username: root
    password: Feilong@1993
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: hope-server-controller
  cloud:
    discovery:
      enabled: true
  profiles:
    active: @start-profile@
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
server:
  port: 4672


logging:
  config:
    classpath: logback-spring.xml

