eureka:
  client:
    service-url:
      defaultZone: http://hopeuser:hopepassword123@mireureka:4670/eureka/
    instance:
      prefer-ip-address: true
      instance-id: hope-controller-client
    fetch-registry: true
    register-with-eureka: true


#在application.yml中加入全局调用的变量是使用instance开头，子类就可以根据要求自己定义了
properties:
  filePath: ${user.home}/data
  ipAddress: http://localhost:4672
instance:
  Service:
    ServiceName: hope-server-service
    ServiceHost: http://localhost:4671