eureka:
  client:
    service-url:
      defaultZone: http://hopeuser:hopepassword123@121.36.66.235:1040/eureka/
    instance:
      prefer-ip-address: true
      instance-id: hope-service-client
    fetch-registry: true
    register-with-eureka: true



