spring:
  application:
    name: micr-eureka-app
    active: hope-mireureka-service
  security:
    basic:
      enable: true
    user:
      name: hopeuser
      password: hopepassword123
server:
  port: 4670
eureka:
  instance:
    appname: ${spring.application.name}
    hostname: mireureka
    prefer-ip-address: false
    #每60秒告诉服务端自己还活着
    lease-renewal-interval-in-seconds: 60
    #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 60
  client:
    register-with-eureka: false
    fetch-registry: false
    #  添加defaultZone时候一定是service-url下的，否则会导致eureka默认的地址配置是http://localhost:8761/eureka
    service-url:
      defaultZone: http://hopeuser:hopepassword123@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #  开启自我保护(默认开启)
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
    renewal-percent-threshold: 0.49


