FROM vertigomedia/ubuntu-jdk8
 
 
ADD *.war /hope-controller.war
EXPOSE 4672

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo "Asia/Shanghai" > /etc/timezone

CMD echo "The application will start in ..." && \
    java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /hope-controller.war
