spring:
  application:
    name: hope-server-gateway
  cloud:
    discovery:
      enabled: true
  profiles:
    active: @start-profile@

server:
  port: 4673

hope:
  header:
    hopeheaderkey: A-Hope-Header-Key
    hopeheadervalue: hope-create-server-value
