spring:
  cloud:
    gateway:
      routes:
      - id: hope-gateway
        uri: http://121.36.66.235:1042/hope-controller/
        predicates:
          - Path=/hope-gateway/**
        filters:
#          不处理请求路径时转发的路由带有hope-gateway前缀，需要去掉该前缀
#          例如： URI：http://localhost:4672/hope-controller/  PATH: /hope-gateway/**
#          当StripPrefix=1时，转发后的路径为：http://localhost:4672/hope-gateway/
#          当StripPrefix=2时，转发后的路径为：http://localhost:4672/
          - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://hopeuser:hopepassword123@120.48.84.17:1024/eureka/
    instance:
      prefer-ip-address: true
      instance-id: hope-gateway-client

