FROM vertigomedia/ubuntu-jdk8
 
 
ADD *.war /hope-gateway.war
EXPOSE 4673
CMD echo "The application will start in ..." && \
    java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /hope-gateway.war
