FROM vertigomedia/ubuntu-jdk8
 
 
ADD *.war /hope-eureka.war
EXPOSE 4670
CMD echo "The application will start in ..." && \
    java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /hope-eureka.war
