spring:
  datasource:
    url: jdbc:mysql://106.13.73.88:3306/littleflydragon?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false
    username: root
    password: feilong@1993
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: hope-service-app
  cloud:
    discovery:
      enabled: true
server:
  port: 4671
eureka:
  client:
    service-url:
      defaultZone: http://hopeuser:hopepassword123@mireureka:4670/eureka/
    instance:
      prefer-ip-address: true
      instance-id: hope-service-client
    fetch-registry: true
    register-with-eureka: true

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.hope.service.*.domain
